### ISSUE TITLE
Broken Link 

### ISSUE THREAD

**Issue by kawedi** [FOSSRIT/people#87]
Hi there, 
This is a [Link](https://github.com/FOSSRIT/people/blob/master/README.md#installation) to “installation” in readme.md 

There is a broken link attached to [Ruby Development Environment](https://github.com/FOSSRIT/people/blob/master/docs/installation) 

Have a nice day, 
Kawedi

**Comment by jwflory** [comment]
I moved this to `FOSSRIT/people` from `FOSSRIT/fossrit.github.io` since it was a documentation bug with this repo.

Thanks for noticing this @kawedi! I pushed pull request #88 with a fix for this, along with some other docs improvements for the People repository. Once that PR merges, this issue will be closed as fixed.
